# Generated by Django 5.0.6 on 2024-06-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='cemento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='casa',
            name='ladrillo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
